# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# set working directory
WORKDIR /app

# Install dependencies separately for caching
COPY package*.json ./

# Install deps, ignoring prepare scripts
RUN npm install --ignore-scripts

# Copy the entire project
COPY . .

# Build the project
RUN npm run build

# Expose port if needed in future, here uses stdio so none

# Start the server using the command from smithery.yaml
CMD ["node", "dist/index.js"]
